 services:
   quick-paw-app:
     build:
       context: .
       args:
         INSTALL_DEV_DEPENDENCIES: "--all-groups"
     env_file:
       - .env
     ports:
       - "8000:8000"
     volumes:
       - ./:/app
     depends_on:
       - quick-paw-db
       - minio
 
   quick-paw-db:
     image: postgres:18.0-alpine3.22
     env_file:
       - .env
     volumes:
       - quick_paw_db_data:/var/lib/postgresql/data
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U quick-paw"]
       interval: 5s
       timeout: 5s
       retries: 5
 
   minio:
     image: minio/minio:RELEASE.2025-09-07T16-13-09Z
     ports:
       - '9000:9000'
       - '9001:9001'
     volumes:
       - 'minio_data:/data'
       - 'minio_config:/root/.minio'
     env_file:
       - .env
     command: minio server /data --console-address ":9001"

 
 volumes:
   quick_paw_db_data:
   minio_data:
   minio_config: