# Generated by Django 5.2.7 on 2025-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_amount_discount_bill_itemsolded'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='size',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
