# Generated by Django 5.2.7 on 2025-10-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_amount_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amount',
            unique_together={('product', 'size')},
        ),
    ]
